
# version format
version: 3.1.0.{build}

# environment
environment:
  majorversion: 3
  minorversion: 1
  patchversion: 0

image: Visual Studio 2017


# Do not build on tags
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: nuget restore src/UIOMatic.sln

build_script:
  - msbuild build/package.proj 
  
artifacts:
  - path: artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: CrjVtUjzvbPn1CgoEwXdeNCtLT8YEeogCxdvKpCz3nM4b5LhNdJ1hmUOm2cLo7JM
  artifact: /.*\.nupkg/
