# version format
version: 3.0.0.{build}

image: Visual Studio 2017


# Do not build on tags
skip_tags: true

before_build:
  - ps: nuget restore src/UIOMatic.sln

build_script:
  - msbuild build/package.proj 

artifacts:
  - path: artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: cRKDqHqagUzMgXLZ971fBXwpacf44O7jsIk7hfeLNo75kShTMknWjQfWLGxgKIPt
  artifact: /.*\.nupkg/
